# Generated by Django 3.1.3 on 2020-12-01 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlient', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('nrtel', models.CharField(help_text='schemat:123-456-789', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('idPracownik', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(help_text='Kilka imion zapisuj po znaku spacji', max_length=100)),
                ('nazwisko', models.CharField(help_text='Nazwiska dwu lub wieloczłonowe pisz po myślniku!', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('nazwa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cena_netto', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('idWizyta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('godzina', models.TimeField(default=datetime.time)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rezerwacje.klient')),
                ('pracownicy', models.ManyToManyField(to='Rezerwacje.Pracownik')),
                ('uslugi', models.ManyToManyField(to='Rezerwacje.Usluga')),
            ],
        ),
    ]
