# Generated by Django 3.1.4 on 2021-01-18 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rezerwacje', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klienci', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='idPracownik',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
